kubernetesClusterDomain: cluster.local
pvc:
  testapiClaim0:
    storageClass: longhorn-rwx
    storageRequest: 100Mi
  testapiClaim1:
    storageClass: longhorn-rwx
    storageRequest: 100Mi
testapi:
  kubetestapi:
    args:
    - uvicorn
    - appb:app
    - --host
    - 0.0.0.0
    - --port
    - "8000"
    - --reload
    env:
      pythonunbuffered: "1"
    image:
      repository: docker.io/matsvitt/kubetestapix
      tag: v6
  ports:
  - name: "8000"
    port: 8000
    targetPort: 8000
  replicas: 1
  strategy:
    type: Recreate
  type: LoadBalancer
