version: '3.8'

services:
  kubetestapi:
    image: docker.io/matsvitt/kubetestapix:v6
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
      - ./datashared:/datashared
    environment:
      - PYTHONUNBUFFERED=1
    command: ["uvicorn", "appb:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
