apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: kubetestapi-claim0
  name: kubetestapi-claim0
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-rwx
  resources:
    requests:
      storage: 100Mi
