apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "kubetestapichart.fullname" . }}-claim2
  labels:
    io.kompose.service: kubetestapi-claim2
  {{- include "kubetestapichart.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.claim2.storageRequest | quote }}
  storageClassName: {{ .Values.pvc.claim2.storageClass | quote }}