apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "kubetestapichart.fullname" . }}-apix
  labels:
  {{- include "kubetestapichart.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: caddy
spec:
  rules:
  - host: kubix1.cookingnumbers.com
    http:
      paths:
      - backend:
          service:
            name: '{{ include "kubetestapichart.fullname" . }}-testapi'
            port:
              number: 8000
        path: /
        pathType: Prefix