apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubetestapichart.fullname" . }}-testapi
  labels:
    io.kompose.service: kubetestapi
  {{- include "kubetestapichart.labels" . | nindent 4 }}
  annotations:
    kompose.cmd: bin/kompose convert
    kompose.version: 1.34.0 (cbf2835db)
spec:
  type: {{ .Values.testapi.type }}
  selector:
    io.kompose.service: kubetestapi
    {{- include "kubetestapichart.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.testapi.ports | toYaml | nindent 2 }}