apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubetestapichart.fullname" . }}-testapi
  labels:
    io.kompose.service: kubetestapi
  {{- include "kubetestapichart.labels" . | nindent 4 }}
  annotations:
    kompose.cmd: bin/kompose convert
    kompose.version: 1.34.0 (cbf2835db)
spec:
  replicas: {{ .Values.testapi.replicas }}
  strategy:
    type: {{ .Values.testapi.strategy.type | quote }}
  selector:
    matchLabels:
      io.kompose.service: kubetestapi
    {{- include "kubetestapichart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        io.kompose.service: kubetestapi
      {{- include "kubetestapichart.selectorLabels" . | nindent 8 }}
      annotations:
        kompose.cmd: bin/kompose convert
        kompose.version: 1.34.0 (cbf2835db)
    spec:
      containers:
      - args: {{- toYaml .Values.testapi.kubetestapi.args | nindent 8 }}
        env:
        - name: PYTHONUNBUFFERED
          value: {{ quote .Values.testapi.kubetestapi.env.pythonunbuffered }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.testapi.kubetestapi.image.repository }}:{{ .Values.testapi.kubetestapi.image.tag
          | default .Chart.AppVersion }}
        name: kubetestapi
        ports:
        - containerPort: 8000
          protocol: TCP
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: kubetestapi-claim0
        - mountPath: /datashared
          name: kubetestapi-claim1
      restartPolicy: Always
      volumes:
      - name: kubetestapi-claim0
        persistentVolumeClaim:
          claimName: {{ include "kubetestapichart.fullname" . }}-testapi-claim0
      - name: kubetestapi-claim1
        persistentVolumeClaim:
          claimName: {{ include "kubetestapichart.fullname" . }}-testapi-claim1