apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "kubetestapichart.fullname" . }}-testapi-claim1
  labels:
    io.kompose.service: kubetestapi-claim1
  {{- include "kubetestapichart.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.pvc.testapiClaim1.storageRequest | quote }}
  storageClassName: {{ .Values.pvc.testapiClaim1.storageClass | quote }}